########################################################
#                  InfoHeads V1.0.0                    #
# - Author: Harry0198                                  #
# - License: FREE!                                     #
#                                                      #
#                 Enjoy the Plugin!                    #
########################################################
# All of your InfoHeads Will be located here!
# PlaceHolderAPI Support coming in later releases
#
# Placeholders: {player-x} {player-y} {player-z} {block-x} {block-y} {block-z} {player-name}
# PlaceHolderAPI Support coming soon
#
# All of your infoheads will appear here. You can edit them but beware when doing so.
Infoheads:
  0:
    location:
      x: 0
      y: 0
      z: 0
      world: "world"
    commands:
      - "say Hello"
      - "say Goodbye"
    messages:
      - "Hi {player-name}"
      - "Bye {player-name}"

